### PR TITLE
[WIP] Add CI environments

### PR DESCRIPTION
**Pull request by rrreeeyyy**
I suggest adding continuous integration environment with wercker.
- [ ] Add `wercker.yml`
- [x] Add this repository to [Wercker](http://wercker.com/)
- [x] Add build status badge to `README.md`

So, would you be so kind as to add this repository to [Wercker](http://wercker.com/)?

### CODE REVIEW

**Comment by nari-ex** [comment]
:+1:

**Comment by nari-ex** [comment]
Please fix readme using below url :bow: 

```
[![wercker status](https://app.wercker.com/status/7c718bb6e4a7d61c3a4fd66c5b863585/s "wercker status")](https://app.wercker.com/project/bykey/7c718bb6e4a7d61c3a4fd66c5b863585)
```

**Comment by rrreeeyyy** [comment]
Thanks. I'll add it. Please wait.

**Comment by nari-ex** [comment]
Failed to build...

```
Failed step: setup environment - No steps defined in the pipeline
```

**Comment by rrreeeyyy** [comment]
I guess the CI failed because of the wercker's environment :cry: 
I'll check it later and try to fix it.

**Pull request closed without merging**
